global:
  k8sEnv: poc-dev1

k8sEnvConfig:
  poc-prod1:
    replicaCount: 5
    affinityKey: Location
    affinityValue: us-east-1
    logicalEnv: prod

  poc-prod2:
    replicaCount: 3
    affinityKey: Location
    affinityValue: us-west-2
    logicalEnv: prod

  poc-qad1:
    replicaCount: 2
    affinityKey: Location
    affinityValue: us-east-1
    logicalEnv: qad

  poc-dev1:
    replicaCount: 1
    affinityKey: Location
    affinityValue: us-east-1
    logicalEnv: dev

service:
  type: ClusterIP
  port: 80

branchIdentifier:
appName: macroservice
applicationImage: gcr.io/heptio-images/ks-guestbook-demo:0.1

# ENV=poc-qad1
# BRANCH_ID=zxc001
# helm template . --namespace=${ENV}-platform --set global.k8sEnv=$ENV --set branchIdentifier=$BRANCH_ID