apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "getBaseName" . }}
  labels:
    app: {{ include "getBaseName" . }}
spec:
  replicas: {{ index .Values.k8sEnvConfig .Values.global.k8sEnv "replicaCount" }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ include "getBaseName" . }}
  template:
    metadata:
      labels:
        app: {{ include "getBaseName" . }}
        deploymentid: time-{{ now | unixEpoch }}
        {{- include "getBasicLabels" . | indent 8 }}
    spec:
      containers:
        - name: {{ include "getBaseName" . }}
          image: "{{ .Values.applicationImage }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: {{ index .Values.k8sEnvConfig .Values.global.k8sEnv "affinityKey" }}
      #           operator: In
      #           values:
      #           - {{ index .Values.k8sEnvConfig .Values.global.k8sEnv "affinityValue" }}