apiVersion: v1
kind: Service
metadata:
  name: {{ include "getBaseName" . }}
  labels:
    app: {{ include "getBaseName" . }}
    {{- include "getBasicLabels" . | indent 4 }}
  annotations:
    kong.athena.io/host: macroservice-clinicals.*
    {{- if .Values.branchIdentifier }}
    kong.athena.io/path: /{{ .Values.branchIdentifier }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ include "getBaseName" . }}
    release: {{ .Release.Name }}
